development:
  adapter: postgresql
  encoding: unicode
  database: codetails_web_audio_api_dev
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: codetails_web_audio_api_test
  host: localhost